/**
 * Mapping des codes categorieJuridiqueUniteLegale (INSEE SIRENE) vers leurs libellés.
 * Source : https://www.insee.fr/fr/information/2028129
 * Liste non exhaustive — codes les plus courants en France.
 */
const FORMES_JURIDIQUES: Record<string, string> = {
  // Personnes physiques
  "1000": "Entrepreneur individuel",
  "1100": "Artisan-commerçant",
  "1200": "Commerçant",
  "1300": "Artisan",
  "1400": "Officier public ou ministériel",
  "1500": "Officier public ou ministériel",
  "1600": "Professionnel libéral",
  "1700": "Agent commercial",
  "1800": "Associé-gérant de société",
  "1900": "Particulier",

  // Groupements de droit privé non dotés de personnalité morale
  "2110": "Indivision entre personnes physiques",
  "2120": "Indivision avec personne morale",
  "2210": "Société créée de fait entre personnes physiques",
  "2220": "Société créée de fait avec personne morale",
  "2310": "Société en participation entre personnes physiques",
  "2320": "Société en participation avec personne morale",

  // Personnes morales de droit privé
  "5100": "SNC — Société en nom collectif",
  "5200": "Société en commandite",
  "5202": "Société en commandite simple",
  "5203": "Société en commandite simple à capital variable",
  "5306": "SA — Société anonyme à directoire",
  "5307": "SA — Société anonyme à conseil d'administration",
  "5308": "SA — Société anonyme NV",
  "5399": "SA",
  "5410": "SA — Société anonyme",
  "5415": "SA à participation ouvrière",
  "5422": "Société anonyme coopérative de production",
  "5426": "Société anonyme coopérative d'intérêt collectif",
  "5430": "Société européenne",
  "5485": "Société d'exercice libéral en commandite par actions",
  "5499": "SAS — Société par actions simplifiée",
  "5500": "SCA — Société en commandite par actions",
  "5505": "SA à capital variable",
  "5510": "SAS — Société par actions simplifiée",
  "5515": "SAS à capital variable",
  "5519": "SAS",
  "5520": "SAS à associé unique — SASU",
  "5569": "SA",
  "5599": "SA",
  "5600": "EURL — Entreprise unipersonnelle à responsabilité limitée",
  "5605": "SARL à capital variable",
  "5610": "SARL — Société à responsabilité limitée",
  "5615": "SARL à associé unique — EURL",
  "5616": "SARL coopérative",
  "5620": "EURL",
  "5622": "SARL coopérative de production",
  "5700": "SARL",
  "5710": "SARL — Société à responsabilité limitée",
  "5720": "EURL — Entreprise unipersonnelle à responsabilité limitée",
  "5770": "Société civile",
  "5785": "Société d'exercice libéral à responsabilité limitée",
  "5800": "Société civile",
  "6100": "Société coopérative agricole",
  "6210": "Groupement agricole d'exploitation en commun",
  "6220": "Groupement foncier agricole",
  "6316": "Coopérative d'utilisation de matériel agricole",
  "7111": "Organisme de placement collectif en valeurs mobilières",
  "7112": "Fonds commun de placement",
  "7113": "Fonds de placement immobilier",
  "7114": "Fonds commun de créances",
  "7120": "Fonds d'investissement",
  "7210": "Association loi 1901",
  "7220": "Association loi 1905 (Alsace-Moselle)",
  "7300": "Fondation",
  "7381": "Association syndicale de propriétaires",
  "7382": "Association foncière urbaine",
  "7389": "Association syndicale libre",
  "7390": "Association syndicale",
  "7450": "Union d'économie sociale",
  "7490": "Groupement d'intérêt économique",
  "8110": "Établissement public national",
  "8210": "Service central d'un ministère",
  "9220": "Commune",
};

export function getFormeJuridiqueLabel(code: string): string | null {
  return FORMES_JURIDIQUES[code] ?? null;
}
