-- ALTER TABLE "services_fm4all_taux" ALTER COLUMN "support_admin" SET DEFAULT 0;--> statement-breakpoint
-- ALTER TABLE "services_fm4all_taux" ALTER COLUMN "min_facturation_support_op" SET DEFAULT 0;--> statement-breakpoint
-- ALTER TABLE "services_fm4all_taux" ALTER COLUMN "min_facturation_account_manager" SET DEFAULT 0;