ALTER TABLE "boissons_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "boissons_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "cafe_conso_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "cafe_machines_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "fontaines_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "fruits_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "fruits_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "hygiene_conso_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "hygiene_conso_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "hygiene_distrib_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "incendie_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "incendie_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "maintenance_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "maintenance_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "nettoyage_repasse_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "nettoyage_repasse_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "nettoyage_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "nettoyage_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "nettoyage_vitrerie_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "nettoyage_vitrerie_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "office_manager_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "office_manager_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "snacks_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
ALTER TABLE "snacks_tarifs" ADD COLUMN "infos" varchar;--> statement-breakpoint
ALTER TABLE "the_conso_tarifs" ADD COLUMN "imageUrl" varchar;--> statement-breakpoint
