ALTER TABLE "alarmes_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "boissons_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "boissons_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "cafe_conso_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "cafe_conso_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "cafe_machines" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "cafe_machines_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "cafe_machines_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "chocolat_conso_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "colonnes_seches_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "exutoires_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "exutoires_parking_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "fontaines" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "fontaines_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "fontaines_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "fruits_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "fruits_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "hygiene_conso_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "hygiene_conso_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "hygiene_distrib_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "hygiene_distrib_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "hygiene_instal_distrib_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "incendie_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "incendie_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "lait_conso_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "legio_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "maintenance_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "maintenance_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "nettoyage_repasse_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "nettoyage_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "nettoyage_vitrerie_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "office_manager_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "office_manager_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "portes_coupe_feu_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "q18_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "qualite_air_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "ria_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "snacks_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "snacks_tarifs" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "sucre_conso_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "the_conso_offres" RENAME COLUMN "imageUrl" TO "image_url";--> statement-breakpoint
ALTER TABLE "the_conso_tarifs" RENAME COLUMN "imageUrl" TO "image_url";