CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "account_provider_account_idx" ON "account" USING btree ("provider_id","account_id");--> statement-breakpoint
CREATE INDEX "alarmes_tarifs_fournisseur_nb_points_idx" ON "alarmes_tarifs" USING btree ("fournisseur_id","nb_points");--> statement-breakpoint
CREATE INDEX "boissons_quantites_gamme_idx" ON "boissons_quantites" USING btree ("gamme");--> statement-breakpoint
CREATE INDEX "boissons_tarifs_fournisseur_gamme_effectif_idx" ON "boissons_tarifs" USING btree ("fournisseur_id","gamme","effectif");--> statement-breakpoint
CREATE INDEX "cafe_conso_tarifs_fournisseur_gamme_effectif_idx" ON "cafe_conso_tarifs" USING btree ("fournisseur_id","gamme","effectif");--> statement-breakpoint
CREATE INDEX "cafe_machines_tarifs_fournisseur_type_nb_personnes_idx" ON "cafe_machines_tarifs" USING btree ("fournisseur_id","type","nb_personnes");--> statement-breakpoint
CREATE INDEX "cafe_machines_tarifs_cafe_machine_id_idx" ON "cafe_machines_tarifs" USING btree ("cafe_machine_id");--> statement-breakpoint
CREATE INDEX "chocolat_conso_tarifs_fournisseur_effectif_idx" ON "chocolat_conso_tarifs" USING btree ("fournisseur_id","effectif");--> statement-breakpoint
CREATE INDEX "clients_email_contact_idx" ON "clients" USING btree ("email_contact");--> statement-breakpoint
CREATE INDEX "clients_siret_idx" ON "clients" USING btree ("siret");--> statement-breakpoint
CREATE INDEX "clients_code_postal_idx" ON "clients" USING btree ("code_postal");--> statement-breakpoint
CREATE INDEX "clients_ville_idx" ON "clients" USING btree ("ville");--> statement-breakpoint
CREATE INDEX "clients_created_at_idx" ON "clients" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "colonnes_seches_tarifs_fournisseur_type_idx" ON "colonnes_seches_tarifs" USING btree ("fournisseur_id","type");--> statement-breakpoint
CREATE INDEX "devis_client_id_idx" ON "devis" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "devis_created_at_idx" ON "devis" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "devis_temporaires_client_id_idx" ON "devis_temporaires" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "devis_temporaires_created_at_idx" ON "devis_temporaires" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "exutoires_parking_tarifs_fournisseur_nb_exutoires_idx" ON "exutoires_parking_tarifs" USING btree ("fournisseur_id","nb_exutoires");--> statement-breakpoint
CREATE INDEX "exutoires_tarifs_fournisseur_nb_exutoires_idx" ON "exutoires_tarifs" USING btree ("fournisseur_id","nb_exutoires");--> statement-breakpoint
CREATE INDEX "fontaines_tarifs_fournisseur_type_nb_personnes_idx" ON "fontaines_tarifs" USING btree ("fournisseur_id","type","nb_personnes");--> statement-breakpoint
CREATE INDEX "fontaines_tarifs_fontaine_id_idx" ON "fontaines_tarifs" USING btree ("fontaine_id");--> statement-breakpoint
CREATE INDEX "food_livraison_tarifs_fournisseur_freq_idx" ON "food_livraison_tarifs" USING btree ("fournisseur_id","freq_annuelle");--> statement-breakpoint
CREATE INDEX "fournisseurs_status_idx" ON "fournisseurs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fournisseurs_siret_idx" ON "fournisseurs" USING btree ("siret");--> statement-breakpoint
CREATE INDEX "fournisseurs_created_at_idx" ON "fournisseurs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "fruits_quantites_gamme_idx" ON "fruits_quantites" USING btree ("gamme");--> statement-breakpoint
CREATE INDEX "fruits_tarifs_fournisseur_gamme_effectif_idx" ON "fruits_tarifs" USING btree ("fournisseur_id","gamme","effectif");--> statement-breakpoint
CREATE INDEX "hygiene_conso_tarifs_fournisseur_effectif_idx" ON "hygiene_conso_tarifs" USING btree ("fournisseur_id","effectif");--> statement-breakpoint
CREATE INDEX "hygiene_distrib_quantites_effectif_idx" ON "hygiene_distrib_quantites" USING btree ("effectif");--> statement-breakpoint
CREATE INDEX "hygiene_distrib_tarifs_fournisseur_idx" ON "hygiene_distrib_tarifs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "hygiene_distrib_tarifs_fournisseur_type_gamme_idx" ON "hygiene_distrib_tarifs" USING btree ("fournisseur_id","type","gamme");--> statement-breakpoint
CREATE INDEX "hygiene_instal_distrib_tarifs_fournisseur_effectif_idx" ON "hygiene_instal_distrib_tarifs" USING btree ("fournisseur_id","effectif");--> statement-breakpoint
CREATE INDEX "hygiene_min_facturation_fournisseur_idx" ON "hygiene_min_facturation" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "incendie_quantites_surface_idx" ON "incendie_quantites" USING btree ("surface");--> statement-breakpoint
CREATE INDEX "incendie_tarifs_fournisseur_surface_idx" ON "incendie_tarifs" USING btree ("fournisseur_id","surface");--> statement-breakpoint
CREATE INDEX "lait_conso_tarifs_fournisseur_effectif_idx" ON "lait_conso_tarifs" USING btree ("fournisseur_id","effectif");--> statement-breakpoint
CREATE INDEX "legio_tarifs_fournisseur_surface_idx" ON "legio_tarifs" USING btree ("fournisseur_id","surface");--> statement-breakpoint
CREATE INDEX "maintenance_quantites_surface_gamme_idx" ON "maintenance_quantites" USING btree ("surface","gamme");--> statement-breakpoint
CREATE INDEX "maintenance_quantites_freq_idx" ON "maintenance_quantites" USING btree ("freq_annuelle");--> statement-breakpoint
CREATE INDEX "maintenance_tarifs_fournisseur_surface_gamme_idx" ON "maintenance_tarifs" USING btree ("fournisseur_id","surface","gamme");--> statement-breakpoint
CREATE INDEX "nettoyage_quantites_gamme_surface_idx" ON "nettoyage_quantites" USING btree ("gamme","surface");--> statement-breakpoint
CREATE INDEX "nettoyage_quantites_freq_idx" ON "nettoyage_quantites" USING btree ("freq_annuelle");--> statement-breakpoint
CREATE INDEX "nettoyage_repasse_tarifs_fournisseur_idx" ON "nettoyage_repasse_tarifs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "nettoyage_repasse_tarifs_fournisseur_surface_gamme_idx" ON "nettoyage_repasse_tarifs" USING btree ("fournisseur_id","surface","gamme");--> statement-breakpoint
CREATE INDEX "nettoyage_tarifs_fournisseur_idx" ON "nettoyage_tarifs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "nettoyage_tarifs_fournisseur_surface_gamme_idx" ON "nettoyage_tarifs" USING btree ("fournisseur_id","surface","gamme");--> statement-breakpoint
CREATE INDEX "nettoyage_vitrerie_tarifs_fournisseur_idx" ON "nettoyage_vitrerie_tarifs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "office_manager_quantites_effectif_surface_idx" ON "office_manager_quantites" USING btree ("effectif","surface");--> statement-breakpoint
CREATE INDEX "office_manager_quantites_gamme_idx" ON "office_manager_quantites" USING btree ("gamme");--> statement-breakpoint
CREATE INDEX "office_manager_tarifs_fournisseur_idx" ON "office_manager_tarifs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "portes_coupe_feu_tarifs_fournisseur_type_idx" ON "portes_coupe_feu_tarifs" USING btree ("fournisseur_id","type");--> statement-breakpoint
CREATE INDEX "q18_tarifs_fournisseur_surface_idx" ON "q18_tarifs" USING btree ("fournisseur_id","surface");--> statement-breakpoint
CREATE INDEX "qualite_air_tarifs_fournisseur_surface_idx" ON "qualite_air_tarifs" USING btree ("fournisseur_id","surface");--> statement-breakpoint
CREATE INDEX "ria_tarifs_fournisseur_idx" ON "ria_tarifs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "services_fm4all_offres_gamme_idx" ON "services_fm4all_offres" USING btree ("gamme");--> statement-breakpoint
CREATE UNIQUE INDEX "services_fournisseurs_uniq" ON "services_fournisseurs" USING btree ("fournisseur_id","service_id");--> statement-breakpoint
CREATE INDEX "services_fournisseurs_fournisseur_idx" ON "services_fournisseurs" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "services_fournisseurs_service_idx" ON "services_fournisseurs" USING btree ("service_id");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "snacks_quantites_gamme_idx" ON "snacks_quantites" USING btree ("gamme");--> statement-breakpoint
CREATE INDEX "snacks_tarifs_fournisseur_gamme_effectif_idx" ON "snacks_tarifs" USING btree ("fournisseur_id","gamme","effectif");--> statement-breakpoint
CREATE INDEX "sucre_conso_tarifs_fournisseur_effectif_idx" ON "sucre_conso_tarifs" USING btree ("fournisseur_id","effectif");--> statement-breakpoint
CREATE INDEX "the_conso_tarifs_fournisseur_gamme_effectif_idx" ON "the_conso_tarifs" USING btree ("fournisseur_id","gamme","effectif");--> statement-breakpoint
CREATE INDEX "user_role_idx" ON "user" USING btree ("role");--> statement-breakpoint
CREATE INDEX "user_fournisseur_id_idx" ON "user" USING btree ("fournisseur_id");--> statement-breakpoint
CREATE INDEX "user_client_id_idx" ON "user" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "verification_expires_at_idx" ON "verification" USING btree ("expires_at");