import { db } from "@/db";
import {
  clientServiceExecutions,
  clientServiceOccurrences,
  clientServiceReglesRecurrence,
  occurrenceFieldLinks,
  occurrenceTaches,
} from "@/db/schema/services";
import { env } from "@/lib/env";
import { snapshotOccurrenceTaches } from "@/server/utils/clientServiceOccurrences.utils";
import { and, count, eq, gte, isNotNull, isNull, lt } from "drizzle-orm";
import type { NextRequest } from "next/server";

/**
 * Cron — Snapshot des tâches + génération des liens terrain.
 *
 * Pour chaque occurrence planifiée dont le début est dans les prochaines 8 jours
 * (aligné sur la fenêtre de matérialisation J+7) et qui a un prestataire assigné :
 *
 * 1. Snapshot les items de la checklist associée (si pas encore fait)
 * 2. Génère un lien terrain (token) si aucun lien actif n'existe déjà
 *
 * Le lien terrain n'est PAS envoyé automatiquement. Il apparaît dans le back-office
 * pour que le responsable_site le copie et le transmette à ses équipes.
 *
 * Idempotent sur les deux opérations.
 *
 * Schedule : "0 21 * * *" (UTC) → 22h heure de Paris (hiver)
 */
export async function GET(request: NextRequest) {
  const authHeader = request.headers.get("authorization");
  if (authHeader !== `Bearer ${env.CRON_SECRET}`) {
    return new Response("Unauthorized", { status: 401 });
  }

  const now = new Date();
  // Fenêtre : prochains 8 jours — aligné sur ensureOccurrencesWindow (daysAhead=7)
  const windowEnd = new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000);

  const occurrences = await db
    .select({
      id: clientServiceOccurrences.id,
      executionId: clientServiceOccurrences.executionId,
      dateDebutPrevue: clientServiceOccurrences.dateDebutPrevue,
      occurrenceTemplateId: clientServiceOccurrences.tacheListeTemplateId,
      regleTemplateId: clientServiceReglesRecurrence.tacheListeTemplateId,
    })
    .from(clientServiceOccurrences)
    .leftJoin(
      clientServiceReglesRecurrence,
      eq(
        clientServiceReglesRecurrence.id,
        clientServiceOccurrences.regleRecurrenceId,
      ),
    )
    .where(
      and(
        eq(clientServiceOccurrences.statut, "planifiee"),
        isNotNull(clientServiceOccurrences.executionId),
        gte(clientServiceOccurrences.dateDebutPrevue, now),
        lt(clientServiceOccurrences.dateDebutPrevue, windowEnd),
      ),
    );

  let snapshotted = 0;
  let snapshotAlreadyDone = 0;
  let snapshotErrors = 0;
  let linksGenerated = 0;
  let linksAlreadyExist = 0;
  let linkErrors = 0;

  for (const occ of occurrences) {
    if (!occ.executionId) continue;

    // ── 1. SNAPSHOT DES TÂCHES ─────────────────────────────────────────────

    const [existing] = await db
      .select({ nb: count() })
      .from(occurrenceTaches)
      .where(
        and(
          eq(occurrenceTaches.occurrenceId, occ.id),
          isNotNull(occurrenceTaches.listeItemId),
        ),
      );

    if ((existing?.nb ?? 0) > 0) {
      snapshotAlreadyDone++;
    } else {
      // Priorité : occurrence > regle > execution
      const templateId =
        occ.occurrenceTemplateId ??
        occ.regleTemplateId ??
        (await db
          .select({
            tacheListeTemplateId: clientServiceExecutions.tacheListeTemplateId,
          })
          .from(clientServiceExecutions)
          .where(eq(clientServiceExecutions.id, occ.executionId))
          .then((rows) => rows[0]?.tacheListeTemplateId ?? null));

      if (templateId) {
        try {
          await snapshotOccurrenceTaches({
            occurrenceId: occ.id,
            tacheListeTemplateId: templateId,
          });
          snapshotted++;
        } catch {
          snapshotErrors++;
        }
      }
    }

    // ── 2. GÉNÉRATION DU LIEN TERRAIN ─────────────────────────────────────
    // Même occurrence, même passe — pas besoin d'un second cron.

    const hasActiveLink = await db
      .select({ nb: count() })
      .from(occurrenceFieldLinks)
      .where(
        and(
          eq(occurrenceFieldLinks.occurrenceId, occ.id),
          isNull(occurrenceFieldLinks.revokedAt),
        ),
      )
      .then((rows) => (rows[0]?.nb ?? 0) > 0);

    if (hasActiveLink) {
      linksAlreadyExist++;
      continue;
    }

    if (!occ.dateDebutPrevue) {
      linkErrors++;
      continue;
    }

    try {
      const token = crypto.randomUUID();
      // Expiration : date de début prévue + 2 jours (marge pour clôture tardive)
      const expiresAt = new Date(
        occ.dateDebutPrevue.getTime() + 2 * 24 * 60 * 60 * 1000,
      );

      await db.insert(occurrenceFieldLinks).values({
        occurrenceId: occ.id,
        token,
        expiresAt,
        autoGenerated: true,
      });

      linksGenerated++;
    } catch {
      linkErrors++;
    }
  }

  return Response.json({
    success: true,
    processed: occurrences.length,
    snapshot: { snapshotted, alreadyDone: snapshotAlreadyDone, errors: snapshotErrors },
    links: { generated: linksGenerated, alreadyExist: linksAlreadyExist, errors: linkErrors },
  });
}
